// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoetsxgylyflviifyizx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvZXRzeGd5bHlmbHZpaWZ5aXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODU3NDEsImV4cCI6MjA3NDY2MTc0MX0.iG9tpZCHl7WrVn-5wh7GZVEoxnzQIAa2a6mMnOom5Ck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});